name: Execute notebook plotting

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # You need ipykernel to solve the "No such kernel named python3" error
        pip install nbconvert ipykernel matplotlib numpy
    - name: Run nbconvert
      run: |
        jupyter nbconvert --execute --to markdown plotting.ipynb
        echo pwd: `pwd`
        ls -alt
        git status
