name: Execute notebook plotting

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # You need ipykernel to solve the "No such kernel named python3" error
        pip install nbconvert ipykernel matplotlib numpy
    - name: Run nbconvert
      run: |
        rm plotting_files/*.png
        jupyter nbconvert --execute --to markdown plotting.ipynb
        echo pwd: `pwd`
        ls -alt
        git status
    - name: Commit files
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add *.md *_files
        if [ -z "$(git status --porcelain)" ]; then
           echo "::set-output name=push::false"
        else
           git commit -m "Update notebook markdowns"
           echo "::set-output name=push::true"
        fi
      shell: bash
    - name: Push changes
      if: steps.commit.outputs.push == 'true'
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: ${{ github.ref }}
